### PR TITLE
Fixed font color for textarea

### LINKED ISSUE #25: Text color makes it unreadable
**Describe the bug**
The color that the text is using makes it unreadable in the right text area.

**To Reproduce**
1. Write any text on the left text area;
2. Click on 'revisar texto' button;
3. See error.

**Expected behavior**
The text should be using the recommended [color theme from Carbon design](https://www.carbondesignsystem.com/guidelines/color/overview#themes). For light themes the text color should be black.

**Screenshots**

Screen Shot 2020-09-08 at 17 03 07

Screen Shot 2020-09-08 at 17 03 23

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 85.0.4183.83

### PR DESCRIPTION
**Pull request by asharonbaltazar**
Fixes #25 

### Overview 
The textarea font-color has been changed to `$carbon--black-100` for visibility. Tested on Edge, Chrome, and Firefox.

image

### CODE REVIEW

**Comment by filipecorrea** [comment]
@camilasb For your review (please ignore the `ERROR`):

Screen Shot 2020-09-09 at 14 09 45

File: src/content/UserPage/UserPage.js [hunk 1]
```diff
@@ -69,9 +69,9 @@ const UserPage = () => {
                   <div className='video-container'>
                     <iframe src='https://player.vimeo.com/video/46398191'
                       title='How it Works'
-                      frameborder='0'
+                      frameBorder='0'
                       allow='autoplay; fullscreen'
-                      allowfullscreen />
+                      allowFullScreen />
```
Comment (filipecorrea) [inline src/content/UserPage/UserPage.js:74]: Those changes are not related to this issue, do you mind opening another issue & pull request for that?

**Review by filipecorrea — CHANGES_REQUESTED** [review]

File: src/content/UserPage/UserPage.js (hunk 1 above)
Comment (asharonbaltazar) [reply src/content/UserPage/UserPage.js:74]: No problem. Should I delete the previous commit then?

**Review by filipecorrea — APPROVED** [review]

**Review by camilasb — APPROVED** [review]
