### PR TITLE
Issue#36 - Connect to local backend

### LINKED ISSUE #36: Connect to the Libras service
**Describe the bug**
The existing code needs to connect to the refactored [Libras service](https://github.com/IBM/libras).

**To Reproduce**
1. Go to the home page;
2. Try to translate a text like "Cap I need because sun strong very.";
3. See error.

**Expected behavior**
This UI must be able to connect to a local instance of the [Libras service](https://github.com/IBM/libras).

**Screenshots**

Screen Shot 2020-09-11 at 17 24 29

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by rdavoli**
Fixes #36

### Overview 
Changes for being able to access a backend that runs locally.

### CODE REVIEW

File: src/content/UserPage/UserPage.js [hunk 1]
```diff
@@ -25,22 +25,23 @@ const UserPage = () => {
       xhr.onreadystatechange = function () {
         if (xhr.readyState === window.XMLHttpRequest.DONE) {
           console.log(xhr.responseText)
+          const responseJSON = JSON.parse(xhr.responseText)
```
Comment (filipecorrea) [inline src/content/UserPage/UserPage.js:28]:
```suggestion
          const response = JSON.parse(xhr.responseText)
```

File: src/content/UserPage/UserPage.js [hunk 2]
```diff
@@ -25,22 +25,23 @@ const UserPage = () => {
       xhr.onreadystatechange = function () {
         if (xhr.readyState === window.XMLHttpRequest.DONE) {
           console.log(xhr.responseText)
```
Comment (filipecorrea) [inline src/content/UserPage/UserPage.js:27]: We should remove this `console.log`.

File: src/content/UserPage/UserPage.js [hunk 3]
```diff
@@ -25,22 +25,23 @@ const UserPage = () => {
...
+          const responseJSON = JSON.parse(xhr.responseText)
           let correctedText = ''
           if (xhr.status === 200) {
             // Format server response
-            correctedText = formatServerOutput(xhr.responseText)
+            correctedText = formatServerOutput(responseJSON.spoken)
```
Comment (filipecorrea) [inline src/content/UserPage/UserPage.js:32]:
```suggestion
            correctedText = formatServerOutput(response.spoken)
```

File: src/content/UserPage/UserPage.js [hunk 4]
```diff
@@ -25,22 +25,23 @@ const UserPage = () => {
...
           } else {
-            correctedText = 'ERROR!!!! ' + xhr.responseText
+            correctedText = 'ERROR!!!! ' + responseJSON.spoken
```
Comment (filipecorrea) [inline src/content/UserPage/UserPage.js:34]:
```suggestion
            correctedText = 'ERROR!!!! ' + response.spoken
```

File: src/content/UserPage/UserPage.js [hunk 5]
```diff
@@ -25,22 +25,23 @@ const UserPage = () => {
...
           }
           outputTextSetValue(correctedText)
         }
         loadingSetValue(false)
       }
-      xhr.open('POST', process.env.REACT_APP_API_SERVICE_URL, true)
+      const url = process.env.REACT_APP_API_SERVICE_URL + '?text=' + JSON.stringify(inputTextValue)
```
Comment (filipecorrea) [inline src/content/UserPage/UserPage.js:40]:
```suggestion
      const url = `${process.env.REACT_APP_API_SERVICE_URL}?text=${JSON.stringify(inputTextValue)}`
```

**Review by filipecorrea — CHANGES_REQUESTED** [review]

**Review by filipecorrea — APPROVED** [review]
