### PR TITLE
Fixed camelCase issue

### LINKED ISSUE #31: Change to camelCase on iframe element
**Describe the bug**
React is reporting the lack of camelCase in `iframe`

**To Reproduce**
1. Open the browser
2. Check dev logs

**Expected behavior**
The logs should be free of React errors

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Edge]
 - Version [v85]

### PR DESCRIPTION
**Pull request by asharonbaltazar**
Fixes #31 

### Overview 
The console has stopped reporting the wrong property names.
Removed line 73, per request.

**Screenshot**
image

### CODE REVIEW

File: src/content/UserPage/UserPage.js [hunk 1]
```diff
@@ -69,9 +69,9 @@ const UserPage = () => {
                   <div className='video-container'>
                     <iframe src='https://player.vimeo.com/video/46398191'
                       title='How it Works'
-                      frameborder='0'
+                      frameBorder='0'
                       allow='autoplay; fullscreen'
```
Comment (filipecorrea) [inline src/content/UserPage/UserPage.js:73]: Can you please remove line 73?

**Review by filipecorrea — CHANGES_REQUESTED** [review]

File: src/content/UserPage/UserPage.js (hunk 1 above)
Comment (asharonbaltazar) [reply src/content/UserPage/UserPage.js:73]: Yeah, sure. Didn't touch other than the warnings though

**Review by filipecorrea — APPROVED** [review]
